- name: Set up local workstation
  hosts: local
  connection: local
  roles:
    - name: osx
      when: ansible_distribution == "MacOSX"
    - name: common
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
