homebrew_taps:
  - homebrew/cask
  - homebrew/cask-fonts
  - heroku/brew

homebrew_packages:
  - curl
  - docker
  - git
  - node
  - python3
  - ruby
  - tmux
  - vim
  - wget
  - zsh

homebrew_cask_packages:
  - flux
  - font-fira-code
  - google-chrome
  - heroku
  - iterm2
  - slack
  - spotify
  - visual-studio-code
