- apt_key:
    url: '{{ item }}'
  with_items: '{{ apt_key_urls }}'
  become: true

- apt_key:
    keyserver: '{{ item.keyserver }}'
    id: '{{ item.id }}'
  with_items: '{{ apt_key_ids }}'
  become: true

- apt_repository:
    repo: '{{ item }}'
  with_items: '{{ apt_repositories }}'
  become: true

- name: Install apt packages
  apt:
    name: '{{ apt_packages }}'
    update_cache: yes
  become: true

- name: Check if deb packages are already installed
  shell: dpkg -s '{{ item.name }}' | grep 'install ok installed' | true
  with_items: '{{ deb_uris }}'
  register: deb_uris_check_result

- name: Install missing deb packages
  apt:
    deb: '{{ item.0.uri }}'
  loop: "{{ deb_uris|zip(deb_uris_check_result.results)|list }}"
  when: item.1.stderr != ""
  become: true

- name: Install snap packages
  snap:
    name: '{{ item }}'
    classic: yes
  with_items: '{{ snap_packages }}'
  become: yes
